## NumPy Arrays

In [1]:
import numpy as np

In [2]:
#creating a one-dimensional array
n1 = np.array([12,41,64,78,93])

print(n1)

[12 41 64 78 93]


In [3]:
#creating a multi-dimensional array
n2 = np.array([[12,41,64,78,93],[2,4,7,1,9],[11,12,13,14,15]])

print(n2)

[[12 41 64 78 93]
 [ 2  4  7  1  9]
 [11 12 13 14 15]]


In [4]:
#creating an array filled with zeros
n3 = np.zeros((4,5))

print(n3)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [5]:
#creating an array filled with a particular number
n4 = np.full((3,4),10)

print(n4)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [6]:
#creating a one-dimensional array within a given range

#array with all elements in a given interval
n5 = np.arange(10,21)
print(n5)

print()

#array with elements with a particular inteval
n6 = np.arange(10,41,5)
print(n6)

[10 11 12 13 14 15 16 17 18 19 20]

[10 15 20 25 30 35 40]


In [7]:
#creating one-dimensional array with random numbers
n7 = np.random.randint(1,100,5)
print(n7)

[42 40  5 86 84]


In [8]:
#checking data type 
type(n1)

numpy.ndarray

In [9]:
#checking shape
print(n1.shape)
print(n2.shape)
print(n3.shape)

(5,)
(3, 5)
(4, 5)


In [10]:
#changing shape
n2.shape=(5,3)
print(n2)
print()
print(n2.shape)

[[12 41 64]
 [78 93  2]
 [ 4  7  1]
 [ 9 11 12]
 [13 14 15]]

(5, 3)


## Joining NumPy arrays

In [11]:
n8 = np.array([1,2,3,4,5])
n9 = np.array([6,7,8,9,10])

In [12]:
#vertical stack
n10 = np.vstack((n8,n9))

print(n10)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [13]:
#horizontal stack
n11 = np.hstack((n8,n9))

print(n11)

[ 1  2  3  4  5  6  7  8  9 10]


In [14]:
#column stack
n12 = np.column_stack((n8,n9))

print(n12)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


## Intersection and Difference of NumPy arrays

In [15]:
n13 = np.array([10,20,30,40,60,90])
n14 = np.array([20,50,60,70,80,100])

In [16]:
#elements in intersection
n15 = np.intersect1d(n13,n14)

print(n15)

[20 60]


In [17]:
#set difference n13-n14
n16 = np.setdiff1d(n13,n14)

print(n16)

[10 30 40 90]


In [18]:
#set difference n14-n13
n17 = np.setdiff1d(n14,n13)

print(n17)

[ 50  70  80 100]


## Sum of NumPy arrays


In [19]:
n18 = np.array([1,3,5,7,9])
n19 = np.array([2,4,6,8,10])

In [20]:
#sum of all elements in an array
np.sum(n18)

25

In [21]:
np.sum([n18,n19])

55

In [22]:
#sum of the columns of [n18,n19]
np.sum([n18,n19],axis=0)

array([ 3,  7, 11, 15, 19])

In [23]:
#sum of the rows of [n18,n19]
np.sum([n18,n19],axis=1)

array([25, 30])

## Basics maths on NumPy arrays

In [24]:
n20 = np.array([10,20,30,40,50])

In [25]:
#basic addition
n20+1

array([11, 21, 31, 41, 51])

In [26]:
#basic subtraction
n20-6

array([ 4, 14, 24, 34, 44])

In [27]:
#basic multiplication
n20*3

array([ 30,  60,  90, 120, 150])

In [28]:
#basic division
n20/5

array([ 2.,  4.,  6.,  8., 10.])

In [29]:
#mean
np.mean(n20)

30.0

In [30]:
#median
np.median(n20)

30.0

In [31]:
#standard deviation
np.std(n20)

14.142135623730951

## Save and load NumPy array

In [32]:
#saving numpy array
n21 = np.array([25,63,82,55,81])
np.save('my_array',n21)

In [33]:
#loading that saved file
n22 = np.load('my_array.npy')

print(n22)

[25 63 82 55 81]
